CREATE TABLE `news` (
   `id` int(11) not null auto_increment,
   `username` varchar(250) not null,
   `headline` text not null,
   `news` text not null,
   `imgName` varchar(250) not null,
   `date` varchar(250) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=13;

INSERT INTO `news` (`id`, `username`, `headline`, `news`, `imgName`, `date`) VALUES 
('1', 'admin', 'The is the bigging of jklsdcjsjv', 'Life : Your life the way you\'ve always wanted to live it. Make new friends, meet people, and lots more... A JavaScript consists of JavaScript statements that are placed within the HTML tags in a web page. You can place the tag containing your JavaScript anywhere within you web page but it is preferred way to keep it within the tags. The tag alert the browser program to begin interpreting all the text between these tags as a script. So simple syntax of your JavaScript will be as follows. An electronic library (also referred to as digital library or digital repository) is a focused collection of digital objects that can include text, visual material, audio material, video material, stored as electronic media formats (as opposed to print, micro form, or other media), along with means for organizing, storing, and retrieving the files and media contained in the library collection. Digital libraries can vary immensely in size and scope, and can be maintained by individuals, organizations, or affiliated with established physical library buildings or institutions, or with academic institutions.[1] The electronic content may be stored locally, or accessed remotely via computer networks. An electronic library is a type of information retrieval system....holumyn', 'news1.jpg', ''),
('2', 'admin', 'inthe dhflhjf sjklfhddsf jklswhfl kjofwhl', 'Life : Your life the way you\'ve always wanted to live it. Make new friends, meet people, and lots more... A JavaScript consists of JavaScript statements that are placed within the HTML tags in a web page. You can place the tag containing your JavaScript anywhere within you web page but it is preferred way to keep it within the tags. The tag alert the browser program to begin interpreting all the text between these tags as a script. So simple syntax of your JavaScript will be as follows. An electronic library (also referred to as digital library or donic library is a type of information retr', 'news2.jpg', ''),
('3', 'holumyn', 'this is my news', 'my news is gud!!!!', 'news3.jpg', ''),
('4', 'holumyn', 'desert', 'this is dersert', 'Desert.jpg', ''),
('5', 'holumyn', 'playing the chess game', 'NETWORKS\nDefinitions: An Interconnected collection of autonomous processors. A Network is a group of\ntwo or more computers connected to each other by a cable, over telephone lines or through\nwireless communication. When you are connected to a network, you can share resources on your\ncomputer such as documents, programs, printers, modems and use other resources from other\ncomputer. The key idea of a Network is that users need equal access to resources such as data,\nbut they do not necessarily have to have equal computing power.\nLANs, WANs and ‘Client Server” concepts are perhaps the most important trend in modern\ncomputing.\nThere are two types of Networks\n&amp;#61623; LOCAL AREA NETWORK (LAN)\n&amp;#61623; WIDE AREA NETWORK (WAN)\nLOCAL AREA NETWORK (LAN)\nDefinition: A network of computers located in a single building or an a single site.\nA LAN may also include a Bridge which is a connection to another similar LAN and a Gateway\nwhich is a connection to a different types of network outside the LAN.\nWIDE AREA NETWORS (WANs)\n- Network on a number of sites, perhaps on a wide geographical scale.\n- WANs often use minicomputers or mainframe as the “pump” that keep the data messages\ncirculating, whereas shorter distance LANs normally use PCs for thin task.\nAirlines are a typical WAN network.\nDIFFERENCES BETWEEN LANs AND WANs\n- The geographical area covered by WANs network is greater, not limited to a single building or\nsite.\n- WANs will send data over telecommunication links, and so will need MODEMS. LANs uses\ndirect cables only for transmitting data.\n- WANs will often use a lager computer a larger computer as a file serve.', 'news1162.jpg', ''),
('6', 'holumyn', 'Library shelf, the best in the world', 'A client –server system allow computer power to be distributed to where it is most needed.\n- A client is a machine which requests a service, e.g. A PC running a spreadsheet application\nwhich the user whishes to print out.\n- A server is a machine which is dedicated to providing a particular function or services\nrequested by a client\n- Servers include file servers, print servers, e-mail servers and LAN servers.\n- The servers provide services such as shared printers, communication links, special-purpose\nprocessing and database storage.\nBENEFIT\n- It reduces network communications costs,\n- It allows the central computer to be used for administrator tasks such as network management.\n- The technological flexibility allows the use of sophisticated applications such as multimedia\nand document image processing (DIP).\nORGANISATION OF NETWORK (NETWORK TOPOLOLIES)\nDefinition: The physical arrangement of nodes in a Network.\n- A Node is any device connected to a Network, it can be a computer, or a peripheral device\nsuch as a printer.\n- Basically, there are four types of LAN system configuration:\nhttp://www.unaab.edu.ng\n* BUS NETWORK *STAR NETWORK\n*RING NETWORK * TREE NETWORK\nBUS NETWORK\n- Messages are sent out from one point along a single communication channel, and the\nmessages are received by other connected machines. Machines only receive messages which\ncontain their unique identifying code.\nRING NETWORK\n-The cable and computer are joined in a ring. There may or may not be a server.\n- Data transmission is normally in one direction only; each interface only copies the data and\npasses it to its own device if it recognize the packets destination as its own.', 'news2510.jpg', ''),
('7', 'holumyn', 'HIERARCHICAL NETWORK (TREE NETWORK)', 'Hierarchical Network consists of nodes organised like a family tree. The top node is a central\ncomputer that is connected to several other nodes which may also be computers. Each of these\nnodes may be connected to several other nodes.\n- Large-scale processing is done by a mainframe, or Mini-computer, and lower-level processing\nby mini computers or micro-computers\nLANS Success is attributed to\n&amp;#61607; Personal computers of sufficient power and related software e.g. UNIIX\n&amp;#61607; Availability of Network at a fairly low price.', 'publications.jpg', ''),
('8', 'admin', 'My app is ready to be deployed', 'This is a very beautiful application developed for the department of computer science federal university of Agriculture,Abeokuta during my stay in the university....i love this app cos it is outstanding...Keepup this great work my fellow nacossite..#PEACE!!!', 'education_careers.jpg', ''),
('9', 'admin', 'facebook: the leading social network', 'facebook is the leading social network', 'fb.png', ''),
('10', 'holu', 'This is my house in miami', 'An electronic procurement system is also known as e-procurement. This term is used to describe software that allows purchasers to access supplier’s catalogs via the Internet, as well as accepting electronic invoices. The purchasers select their materials, indicate the accounts to be charged for the purchase, and create a purchase order in the accounting system. All procurement-related activity is completed in the electronic system, reducing paperwork and increasing efficiency.\r\nElectronic invoice processing allows selected companies to further streamline invoice review and approval. The data is then routed through a series of online approvals before being processed for payment in the accounting system. This type of procurement system is very popular in large firms, where procurement contracts are in place to manage spending activity. For these firms, the reduction in staff time for invoice processing provides an excellent return on investment.\r\n', 'Lighthouse.jpg', 'Jul 15 2014'),
('11', 'admin', 'nice pix baby', 'i love this', '300x300(12).jpg', 'Jul 31,2014'),
('12', 'admin', 'beautifull people', 'beautiful people ......', '300x300(26).jpg', 'Jul 31,2014');